### ISSUE TITLE
there seems to be an issue with the file package

### ISSUE THREAD

**Issue by myfoxtail** [solvexia/solvexia-python-sdk#16]
I had to comment out the package used for uploading by chunks - that did not get installed as part of the pip install of solvexia_sdk, and if I tried to install it stand-alone it failed too.  Maybe the sdk was tested with Python 2 instead of 3?

```
C:\Users\nick>pip install fsplit
Collecting fsplit
  Using cached fsplit-1.0.0.tar.gz (7.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ nick\AppData\Local\Temp\pip-install-2xu93pfk\fsplit_d8ff75c944174112be76b04052b7ed61\setup.py", line 11, in <module>
          from fsplit import __version__
        File "C:\Users\ nick\AppData\Local\Temp\pip-install-2xu93pfk\fsplit_d8ff75c944174112be76b04052b7ed61\fsplit\__init__.py", line 11, in <module>
          from info import __version__ # define __version__ variable
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'info'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by alex-solvexia** [comment]
We need to update a version of `filesplit` (https://pypi.org/project/filesplit/) to the latest one and change the import code. @Womokoshi can you please look into this?
